export enum SUBSCRIPTION {
  UNSUBSCRIBED = "UNSUBSCRIBED",
  INPROGRESS = "INPROGRESS",
  SUBSCRIBED = "SUBSCRIBED",
  REJECTED = "REJECTED",
}


export enum INVEST {
  INPROGRESS = "INPROGRESS",
  MINTED = "MINTED",
  REJECTED = "REJECTED",
}
